name: 'Deploy'
description: 'Deploy Terraform configuration to Cloudflare'

inputs:
  CLIENT_ID:
    description: 'The client ID of the service principal used to login to Azure'
    required: true

  TENANT_ID:
    description: 'The Azure AD tenant ID'
    required: true

  SUBSCRIPTION_ID:
    description: 'The Azure subscription ID'
    required: true

  ENVIRONMENT:
    description: 'The environment to deploy to'
    required: true

  CLOUDFLARE_API_TOKEN:
    description: 'The Cloudflare API token'
    required: true

  CLOUDFLARE_ZONE_ID:
    description: 'The Cloudflare zone ID'
    required: true

  CLOUDFLARE_ACCOUNT_ID:
    description: 'The Cloudflare account ID'
    required: true

  CLOUDFLARE_ACCESS_KEY_ID:
    description: 'The Cloudflare access key ID'
    required: true

  CLOUDFLARE_SECRET_ACCESS_KEY:
    description: 'The Cloudflare secret access key'
    required: true

  DOMAIN_NAME:
    description: 'The domain name'
    required: true

  RESOURCE_GROUP_NAME:
    description: 'The name of the resource group for AKS'
    required: true

  AKS_CLUSTER_NAME:
    description: 'The name of the AKS cluster'
    required: true

runs:
  using: 'composite'
  steps:
    # Set Environment Variables for Cloudflare R2 Storage as Backend
    - name: Set Environment Variables
      shell: bash
      run: |
        echo "AWS_ACCOUNT_ID=${{ inputs.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=${{ inputs.CLOUDFLARE_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.CLOUDFLARE_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "CLOUDFLARE_API_TOKEN=${{ inputs.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
        echo "CLOUDFLARE_ACCOUNT_ID=${{ inputs.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ inputs.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        DOMAIN_NAME: ${{ inputs.DOMAIN_NAME }}
      run: |
        terraform -chdir=terraform/cloudflare/envs/${{ inputs.ENVIRONMENT }} init \
        -var environment=${{ inputs.ENVIRONMENT }} \
        -var cloudflare_api_token=$CLOUDFLARE_API_TOKEN \
        -var cloudflare_zone_id=$CLOUDFLARE_ZONE_ID \
        -var cloudflare_account_id=$CLOUDFLARE_ACCOUNT_ID \
        -var domain_name=$DOMAIN_NAME

    # Terraform Validate
    - name: Terraform Validate
      shell: bash
      run: terraform -chdir=terraform/cloudflare/envs/${{ inputs.ENVIRONMENT }} validate -no-color

    - name: Terraform Plan
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ inputs.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        DOMAIN_NAME: ${{ inputs.DOMAIN_NAME }}
      run: |
        terraform -chdir=terraform/cloudflare/envs/${{ inputs.ENVIRONMENT }} plan \
        -no-color \
        -var environment=${{ inputs.ENVIRONMENT }} \
        -var cloudflare_api_token=$CLOUDFLARE_API_TOKEN \
        -var cloudflare_zone_id=$CLOUDFLARE_ZONE_ID \
        -var cloudflare_account_id=$CLOUDFLARE_ACCOUNT_ID \
        -var domain_name=$DOMAIN_NAME

    # Terraform Apply
    - name: Terraform Apply
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ inputs.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        DOMAIN_NAME: ${{ inputs.DOMAIN_NAME }}
      run: |
        terraform -chdir=terraform/cloudflare/envs/${{ inputs.ENVIRONMENT }} apply \
        -auto-approve \
        -var environment=${{ inputs.ENVIRONMENT }} \
        -var cloudflare_api_token=$CLOUDFLARE_API_TOKEN \
        -var cloudflare_zone_id=$CLOUDFLARE_ZONE_ID \
        -var cloudflare_account_id=$CLOUDFLARE_ACCOUNT_ID \
        -var domain_name=$DOMAIN_NAME

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.CLIENT_ID }}
        tenant-id: ${{ inputs.TENANT_ID }}
        subscription-id: ${{ inputs.SUBSCRIPTION_ID }}

    - name: Set AKS Credentials
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ inputs.RESOURCE_GROUP_NAME }}
        cluster-name: ${{ inputs.AKS_CLUSTER_NAME }}

    # Set Terraform Output as Variable
    - name: Terraform Output
      shell: bash
      run: |
        tunnel_name=$(terraform -chdir=terraform/cloudflare/envs/${{ inputs.ENVIRONMENT }} output tunnel_name)
        tunnel_secret=$(terraform -chdir=terraform/cloudflare/envs/${{ inputs.ENVIRONMENT }} output secret)
        tunnel_id=$(terraform -chdir=terraform/cloudflare/envs/${{ inputs.ENVIRONMENT }} output tunnel_id)
        echo "tunnel_name=$tunnel_name" >> $GITHUB_ENV
        echo "tunnel_secret=$tunnel_secret" >> $GITHUB_ENV
        echo "tunnel_id=$tunnel_id" >> $GITHUB_ENV

    # Set Tunnel Name
    - name: Set Tunnel Name
      shell: bash
      run: |
        #cloudflared=$(cat ./manifest/container/cloudflared.yaml | \
        #sed "s/<TunnelName>/${{ env.tunnel_name }}/g")
        #echo "$cloudflared" > ./manifest/container/cloudflared.yaml
        sed -e "s/<TunnelName>/${{ env.tunnel_name }}/g" ./manifest/container/cloudflared.yaml) > ./manifest/container/cloudflared.yaml

    # Set Tunnel Credentials
    - name: Set Tunnel Credentials
      shell: bash
      run: |
        credentials=$(cat ./manifest/credential/credential.json | \
        sed -e "s/<AccountTag>/${{ inputs.CLOUDFLARE_ACCOUNT_ID }}/g" | \
        sed -e "s/<TunnelSecret>/${{ env.tunnel_secret }}/g" | \
        sed -e "s/<TunnelID>/${{ env.tunnel_id }}/g")
        echo "$credentials" > ./manifest/credential/credential.json

    # Set credentials for Cloudflare Tunnel
    - name: Set Cloudflare Tunnel Credentials
      shell: bash
      run: |
        kubectl create secret generic tunnel-credentials --from-file=credentials.json=./manifest/credential/credential.json

    # Deploy Cloudflare Tunnel
    - name: Deploy Cloudflare Tunnel
      shell: bash
      run: |
        kubectl apply -f ./manifest/container/cloudflared.yaml