name: 'Terraform Cloudflare Destory Develop'

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/heads/feature/') && github.ref != 'refs/heads/main' && github.base_ref != 'refs/heads/main'}}
    steps:
    - name: Unknown Branch
      run: exit 1

  terraform-cf-destroy:
    runs-on: ubuntu-latest
    environment: develop
    if: ${{ startsWith(github.ref, 'refs/heads/feature/') || github.ref == 'refs/heads/main' || github.base_ref == 'refs/heads/main'}}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Destroy
      uses: ./.github/actions/destroy
      with:
        ENVIRONMENT: ${{ vars.ENVIRONMENT }}
        BACKEND_ENDPOINT: ${{ secrets.BACKEND_ENDPOINT }}
        BACKEND_BUCKET: ${{ vars.BACKEND_BUCKET }}
        BACKEND_KEY: ${{ vars.BACKEND_KEY }}
        BACKEND_REGION: ${{ vars.BACKEND_REGION }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
        CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}