name: 'Kubernetes Deploy'
concurrency: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_number }}

on:
  push:
    branches:
    - main
    paths: ['manifest/**', '.github/workflows/tf-k8s-deploy.yml']
  pull_request:
    branches:
    - main
    paths: ['manifest/**', '.github/workflows/tf-k8s-deploy.yml']

env:
  AZURE_CREDENTIAL: ${{ secrets.AZURE_CREDENTIAL }}
  manifest_path: './manifest'

jobs:
  deploy-container:
    name: 'Apply AKS manifest'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}

      - name: AKS Get Credential
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az aks get-credentials --admin --admin --overwrite-existing \
            --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
            --name ${{ vars.AKS_CLUSTER_NAME }}
            --file ./kube/${{ vars.AKS_CLUSTER_NAME }}

      - name: Apply manifest
        run: |
          kubectl apply -k ${{ env.manifest_path}} \
          --kubeconfig ./kube/${{ vars.AKS_CLUSTER_NAME }}