name: 'Terraform Plan/Apply'

on:
  push:
    branches:
    - main
    paths: ['terraform/aks/**', '.github/workflows/tf-plan-apply.yml']

  pull_request:
    branches:
    - main
    paths: ['terraform/aks/**', '.github/workflows/tf-plan-apply.yml']

#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
  WORKING_DIRECTORY: "terraform/aks"

defaults:
  run:
    working-directory: "./terraform/aks"

jobs:                
  terraform-apply:
    name: 'Terraform Apply'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: productio
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      env:
        BACKEND_RESOURCE_GROUP_NAME: ${{ vars.BACKEND_RESOURCE_GROUP_NAME }}
        BACKEND_STORAGE_ACCOUNT_NAME: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
        BACKEND_CONTAINER_NAME: ${{ vars.BACKEND_CONTAINER_NAME }}
        BACKEND_KEY: ${{ vars.BACKEND_KEY }}
      run: |
        terraform init \
        -backend-config="backend_resource_group_name=$BACKEND_RESOURCE_GROUP_NAME" \
        -backend-config="backend_storage_account_name=$BACKEND_STORAGE_ACCOUNT_NAME" \
        -backend-config="backend_container_name=$vars.BACKEND_CONTAINER_NAME" \
        -backend-config="backend_key=$vars.BACKEND_KEY"
    
    # Checks that all Terraform configuration files adhere to a canonical format
    # Will fail the build if not
    - name: Terraform Format
      run: terraform fmt -check

    #Terraform Plan
    - name: Terraform Plan
      env:
        BACKEND_RESOURCE_GROUP_NAME: ${{ vars.BACKEND_RESOURCE_GROUP_NAME }}
        BACKEND_STORAGE_ACCOUNT_NAME: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
        BACKEND_CONTAINER_NAME: ${{ vars.BACKEND_CONTAINER_NAME }}
        BACKEND_KEY: ${{ vars.BACKEND_KEY }}
      run: |
        terraform init \
        -var backend_resource_group_name=$BACKEND_RESOURCE_GROUP_NAME \
        -var backend_storage_account_name=$BACKEND_STORAGE_ACCOUNT_NAME \
        -var backend_container_name=$vars.BACKEND_CONTAINER_NAME \
        -var backend_key=$vars.BACKEND_KEY

    # Terraform Apply
    - name: Terraform Apply
      env:
        BACKEND_RESOURCE_GROUP_NAME: ${{ vars.BACKEND_RESOURCE_GROUP_NAME }}
        BACKEND_STORAGE_ACCOUNT_NAME: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
        BACKEND_CONTAINER_NAME: ${{ vars.BACKEND_CONTAINER_NAME }}
        BACKEND_KEY: ${{ vars.BACKEND_KEY }}
      run: |
        terraform init \
        -var backend_resource_group_name=$BACKEND_RESOURCE_GROUP_NAME \
        -var backend_storage_account_name=$BACKEND_STORAGE_ACCOUNT_NAME \
        -var backend_container_name=$vars.BACKEND_CONTAINER_NAME \
        -var backend_key=$vars.BACKEND_KEY